// photoName = (2)name+(3)surname
export const TEAM = [
    { allClimbId: null , year: null  , photoName: 'ankya', name: 'Анастасия Кярова', isCoach: true },
    { allClimbId: 46994, year: '2009', photoName: 'arboc', name: 'Арина Бочкова', isCityTeam: true },
    { allClimbId: 54839, year: '2008', photoName: 'mabri', name: 'Марина Бриллиантова' },
    { allClimbId: null , year: '2010', photoName: 'madas', name: 'Маша Дашкевич' },
    { allClimbId: 54736, year: '2009', photoName: 'vadia', name: 'Варя Дьячкова', isCityTeam: true },
    { allClimbId: null , year: '2012', photoName: 'vaevd', name: 'Ваня Евдокимов' },
    { allClimbId: 47913, year: '2011', photoName: 'glere', name: 'Глеб Еремин', isCityTeam: true },
    { allClimbId: null , year: '2010', photoName: 'efrit', name: 'Ефимова Рита', isCityTeam: true },
    { allClimbId: null , year: '2012', photoName: 'stzur', name: 'Стася Зырянова', isCityTeam: true },
    { allClimbId: null , year: '2013', photoName: 'soiva', name: 'Соня Иваненко' },
    { allClimbId: 35292, year: '2013', photoName: 'vikon', name: 'Витя Кондрашин', isCityTeam: true },
    { allClimbId: 55862, year: '2011', photoName: 'armaj', name: 'Арина Мажара', isCityTeam: true },
    { allClimbId: null , year: '2011', photoName: 'somak', name: 'Соня Маковкина', isCityTeam: true },
    { allClimbId: null , year: '2010', photoName: 'armar', name: 'Арина Мартьянова' },
    { allClimbId: null , year: '2013', photoName: 'komat', name: 'Коля Матвеев' },
    { allClimbId: 49224, year: '2012', photoName: 'samis', name: 'Саша Мишан', isCityTeam: true },
    { allClimbId: 24178, year: '2012', photoName: 'samok', name: 'Саша Мокруша', isCityTeam: true },
    { allClimbId: null , year: '2011', photoName: 'timun', name: 'Тима Мунин', isCityTeam: true },
    { allClimbId: null , year: '2011', photoName: 'runaz', name: 'Рудольф Назаров', isCityTeam: true },
    { allClimbId: null , year: '2013', photoName: 'vaodn', name: 'Ваня Однодворцев' },
    { allClimbId: null , year: '2010', photoName: 'kipop', name: 'Кира Попова' },
    { allClimbId: null , year: '2012', photoName: 'marud', name: 'Марк Рудов' },
    { allClimbId: null , year: '2010', photoName: 'rorud', name: 'Рома Руднев' },
    { allClimbId: null , year: '2009', photoName: 'kista', name: 'Кирилл Стародубцев' },
    { allClimbId: null , year: '2011', photoName: 'ulsta', name: 'Ульяна Стародубцева' },
    { allClimbId: null , year: '2012', photoName: 'rotar', name: 'Родион Таросенко' },
    { allClimbId: null , year: '2014', photoName: 'ulche', name: 'Юля Червонцева' },
    { allClimbId: null , year: '2014', photoName: 'jeyar', name: 'Женя Ярославцев' },
];