export const TEAM = [
    { allClimbId: 46994,     year: '2009', name: 'Арина Бочкова', isCityTeam: true },
    { allClimbId: 54839,     year: '2008', name: 'Марина Бриллиантова' },
    { allClimbId: undefined, year: '2010', name: 'Маша Дашкевич' },
    { allClimbId: 54736,     year: '2009', name: 'Варя Дьячкова', isCityTeam: true },
    { allClimbId: undefined, year: '2012', name: 'Ваня Евдокимов' },
    { allClimbId: 47913,     year: '2011', name: 'Глеб Еремин', isCityTeam: true },
    { allClimbId: undefined, year: '2010', name: 'Ефимова Рима', isCityTeam: true },
    { allClimbId: undefined, year: '2012', name: 'Стася Зырянова', isCityTeam: true },
    { allClimbId: undefined, year: '2013', name: 'Соня Иваненко' },
    { allClimbId: 35292,     year: '2013', name: 'Витя Кондрашин', isCityTeam: true },
    { allClimbId: 55862,     year: '2011', name: 'Арина Мажара', isCityTeam: true },
    { allClimbId: undefined, year: '2011', name: 'Соня Маковкина', isCityTeam: true },
    { allClimbId: undefined, year: '2010', name: 'Арина Мартьянова' },
    { allClimbId: undefined, year: '2013', name: 'Коля Матвеев' },
    { allClimbId: 49224,     year: '2012', name: 'Саша Мишан', isCityTeam: true },
    { allClimbId: 24178,     year: '2012', name: 'Саша Мокруша', isCityTeam: true },
    { allClimbId: undefined, year: '2011', name: 'Тима Мунин', isCityTeam: true },
    { allClimbId: undefined, year: '2011', name: 'Рудольф Назаров', isCityTeam: true },
    { allClimbId: undefined, year: '2013', name: 'Ваня Однодворцев' },
    { allClimbId: undefined, year: '2010', name: 'Кира Попова' },
    { allClimbId: undefined, year: '2012', name: 'Марк Рудов' },
    { allClimbId: undefined, year: '2010', name: 'Рома Руднев' },
    { allClimbId: undefined, year: '2009', name: 'Кирилл Стародубцев' },
    { allClimbId: undefined, year: '2011', name: 'Ульяна Стародубцева' },
    { allClimbId: undefined, year: '2012', name: 'Родион Таросенко' },
    { allClimbId: undefined, year: '2014', name: 'Юля Червонцева' },
    { allClimbId: undefined, year: '2014', name: 'Женя Ярославцев' },
];